### ISSUE TITLE
Not enabling device

### ISSUE THREAD

**Issue by tylernealyum** [rgov/Thunderbolt3Unblocker#10]
I have a Dell TB16 dock that was previously working using the TB3-Enabler patch, I updated to 10.13.4 this morning and was unable to get it to work using that patch so I tried this one, I have the kext loaded but the dock still isn't working for me.  What is a good first troubleshooting step?

**Comment by rgov** [comment]
Look at your System Profile and see what it says under the Thunderbolt device tree—does it list the dock? Is it still listed as "Unsupported"?

Note that you need to connect the device after the extension has loaded.

**Comment by tylernealyum** [comment]
Validated that the kext was loaded, see screenshot, checked system profile and it's saying "No drivers are loaded" for thunderbolt.
![kext](https://user-images.githubusercontent.com/20650175/38228082-628d74ce-36b6-11e8-819d-c92a6996912b.png)
![systemprofile](https://user-images.githubusercontent.com/20650175/38228083-62a0095e-36b6-11e8-8fe8-1090adce9c9b.png)

**Comment by rgov** [comment]
It looks like this problem is unrelated to Thunderbolt 3 Unblocker. Even on my MacBook Pro when no Thunderbolt devices are attached, the Thunderbolt page of System Profiler shows "Thunderbolt Bus 0" and "Thunderbolt Bus 1," but yours looks as though the system is not even aware at all of the Thunderbolt capabilities.

I would uninstall any patched drivers (including Thunderbolt 3 Unblocker), NVRAM settings, etc. and get your Mac back to the shipping state. For instance, you can re-install macOS from the Recovery OS, and delete any third-party drivers.

Then see if your Thunderbolt bus is showing up. _Then_, if and only if the dock shows up in System Profiler with the word "Unsupported" next to it, you can use Thunderbolt 3 Unblocker.

Also please note that macOS 10.13.4 changed some behaviors regarding [older Thunderbolt devices](https://appleinsider.com/articles/18/03/14/thunderbolt-thunderbolt-2-egpu-compatibility-purged-from-macos-high-sierra-beta-5).
