### ISSUE TITLE
No video from Dell TB16 dock

### ISSUE THREAD

**Issue by azabecki** [rgov/Thunderbolt3Unblocker#11]
Thank you for your efforts! I have built and loaded the kext. It now sees my Dell TB16 dock. Ethernet, audio and all USB ports are working fine. However, no video at all from the dock, from any of the ports. (HDMI, Displayport, and MiniDisplayport). Please advise?

**Comment by rgov** [comment]
I'm sorry, but this one is beyond me—I only know how to bypass the compatibility check, but I don't know much about specific Thunderbolt accessories and their level of support on macOS. It is currently beyond the scope of Thunderbolt 3 Unblocker to modify the behavior of any particular device.

Once the check is bypassed, macOS asks the dock what devices are connected to it, and then sees if there is a driver available for each device. Drivers can opt-out of being tunneled over Thunderbolt 3, but I would not expect that to happen here. You can try setting the `npci=0x80000` boot-arg (from the Recovery OS, if SIP is not disabled), which will force all drivers to tunnel.

Also try first plugging in the display to the dock and second plugging it into your Mac, maybe the order matters?

If you do figure it out, please report back so that others can learn, but I'm afraid I don't know much more to say.

**Comment by adriantoine** [comment]
Here is what I found:
https://plugable.com/2018/03/30/macos-10-13-4-disables-displaylink-duet-display-devices/

If your display on a dock doesn't work with 10.13.4, the best way is to revert to the previous Mac OS version.

**Comment by mehmetenes** [comment]
TB16 is not a DisplayLink device. I have the same one and it was working fine with tb3-enabler some time ago and it's stopped after an update to MacOS. So, it has nothing to do with this unlocker I assume. I still have no clue why it's stopped but it simply doesn't work anymore.
