### ISSUE TITLE
Mouse become laggy every 5 seconds

### ISSUE THREAD

**Issue by gekowa** [rgov/Thunderbolt3Unblocker#16]
I'm using a HP TB3 Dock, and I installed the amazing TB3Unblocker. But it seems that the mouse (the Trackpad, too) laggy for about 500ms every around 5 seconds. I don't know if this is a problem of the TB3Unblocker itself, but the system become fine after I uninstalled, of course, the dock become "unsupported" again.

**Comment by rgov** [comment]
Thanks for reporting this issue. It does not sound to me like it could possibly be caused by Thunderbolt 3 Unblocker, because it only does anything (i) when the extension is loaded (say, during system startup), and (ii) at the time you plug in a Thunderbolt 3 peripheral. Both times it takes only a fraction of a second.

What is possibly happening is that, now your dock is enabled, the system will look at what devices are plugged into the dock, and load the corresponding drivers. So can you see if the problem happens with the dock plugged into your Mac, but nothing plugged into the dock?

**Comment by gekowa** [comment]
Thanks for reply, I think you're right, I disconnected the VGA port and the system becomes fine.
