### ISSUE TITLE
Doesn't work for 10.14.4

### ISSUE THREAD

**Issue by CentralArkansasHackers** [rgov/Thunderbolt3Unblocker#35]
Output:
Kext with invalid signatured (-67050) allowed: <OSKext 0x7ff215a51b50 [0x7fff9151a8f0]> { URL = "Thunderbolt3Unblocker.kext/ -- file:///Library/Extensions/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
Kext with invalid signatured (-67054) allowed: <OSKext 0x7ff210e7c240 [0x7fff9151a8f0]> { URL = "IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.iokit.IOThunderboltFamily" }
KernelCache ID: 4E6CD4DB56CC597DE5057798BCC87832
Kext with invalid signatured (-67054) allowed: <OSKext 0x7fbd1c1beee0 [0x7fff9151a8f0]> { URL = "IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.iokit.IOThunderboltFamily" }
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fbd1d8e93c0 [0x7fff9151a8f0]> { URL = "Thunderbolt3Unblocker.kext/ -- file:///Library/Extensions/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }

From system report:

 Vendor Name:	Dell
  Device Name:	Dell Thunderbolt Cable
  Vendor ID:	0xD4
  Device ID:	0xB051
  Device Revision:	0x1
  UID:	0x8086A32094118610
  Route String:	1
  Firmware Version:	15.15

No throughput for ethernet or usb

**Comment by rgov** [comment]
I have tested under macOS 10.14.4 and do not see this issue.

Please open System Report, under Thunderbolt, and look at the device tree (at the top of the window). If none of the devices say "Unsupported", then Thunderbolt3Unblocker is working fine.

If some device *does* say "Unsupported", please unplug and plug them back in and select File → Refresh Information. If the "Unsupported" does not go away, please comment here and I'll re-open the issue. (Include a screenshot, if possible.)

Note that Thunderbolt3Unblocker merely unblocks the device so that other macOS drivers can use it. If macOS does not know how to speak to your device, T3U will not help. It does not know anything about your device itself.

**Comment by rgov** [comment]
Also there is an existing issue for the Dell TB15, if that is the device you are dealing with: https://github.com/rgov/Thunderbolt3Unblocker/issues/33
