### ISSUE TITLE
Mojave 10.14.6 Beta (18G29g) 

### ISSUE THREAD

**Issue by csitarichie** [rgov/Thunderbolt3Unblocker#39]
my system updated to 10.14.6 Beta (18G29g) and the TB16 Dell dock does not work any more.
I have disabled the kext security restrictions and reloaded the kernel patch there was no error on the terminal. but only the dell cable is recognised. 

See :
Dell Thunderbolt Cable:

  Vendor Name:	Dell
  Device Name:	Dell Thunderbolt Cable
  Vendor ID:	0xD4
  Device ID:	0xB051
  Device Revision:	0x2
  UID:	0x00D4461D6D817600
  Route String:	1
  Firmware Version:	16,16
  Port (Upstream):
  Status:	Device connected
  Link Status:	0x2
  Speed:	Up to 40Gb/s x1
  Current Link Width:	0x2
  Link Controller Firmware Version:	0.25.0
  Port:
  Status:	No device connected
  Link Status:	0x7
  Speed:	Up to 40Gb/s x1
  Current Link Width:	0x1
  Link Controller Firmware Version:	0.25.0

Can you please tell me how to collect more log form kernel loading to give more debug.

**Comment by rgov** [comment]
I do not see the word "(Unsupported)" in the above output so it appears to be that Thunderbolt 3 Unblocker has done its job.

T3U only unblocks the device; other drivers installed to the system then need to do their job to *talk* to the device. If Apple has changed what their drivers are willing to talk to, it may explain the problem.

Please see [this issue](https://github.com/rgov/Thunderbolt3Unblocker/issues/28) for a general discussion of the TB16 and how others have gotten it to work. I don't know if you mean that the video output doesn't work, or if that includes all downstream devices, e.g., the USB ports.

I'll close this because there's nothing for me to do, but if you want to provide more output, feel free to unload the kernel extension, `kextload` it, and then immediately run `dmesg` to get the output, and attach it here. It will confirm for certain that patching was successful.

**Comment by csitarichie** [comment]
Before the update by TB16 just worked fine ... :(. I will post the dmesg output to be sure. 
Thanks.

**Comment by csitarichie** [comment]
Update it is still working ... even with the new Mojave beta ... just the dock itself is unstable and it needed a power cycle as well. Sorry for the bother.
