### ISSUE TITLE
macOS Catalina

### ISSUE THREAD

**Issue by rgov** [rgov/Thunderbolt3Unblocker#42]
There has been one unconfirmed report that Thunderbolt 3 Unblocker does not install on macOS 10.15 "Catalina."

If you are having difficulty installing and using Thunderbolt 3 Unblocker on Catalina, please follow the [troubleshooting guide](https://github.com/rgov/Thunderbolt3Unblocker/wiki/Troubleshooting) and report here whether you are able to get it to work or not.

**Update:** Users have reported success using Thunderbolt 3 Unblocker on macOS 10.15 beta 8.

**Comment by exeliser** [comment]
Hi everyone, Just wanted to let you know that there seems to be an issue with the latest updates of Catalina wherein the TB16 will not function any longer. I am clueless as to why and looking into it. Anyone any tips. All systems are operating normally and the cable is recognised but nothing further down the line.

**Comment by rgov** [comment]
Please tell me more like what device you are using and upload diagnostics requested in the Troubleshooting guide on the wiki. Thanks.

**Comment by exeliser** [comment]
[t3u-diagnose.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/3626577/t3u-diagnose.txt)
MacBook Pro 2017 15"

**Comment by rgov** [comment]
And what is the Thunderbolt device?

**Comment by exeliser** [comment]
The TB16 from dell. Which worked 2 weeks ago but after auto updating catalina not anylonger.

**Comment by rgov** [comment]
Thanks @exeliser. Your diagnostics file tells me that Thunderbolt 3 Unblocker works OK on Catalina. But something else has changed in the system to not support the TB16. This is the most problematic Thunderbolt device (#28).

**Comment by exeliser** [comment]
How can we fix this?

**Comment by rgov** [comment]
I do not have a TB16 so I cannot diagnose it. T3U works by simply *allowing* the system to talk to a peripheral, but it cannot *force* the system to talk to that peripheral. Importantly, the system needs the correct drivers installed for video, USB, etc.

I would look for another dock that is supported.

**Comment by korotkov13** [comment]
I confirm that Thunderbolt 3 Unblocker is working in Catalina with TB15.

**Comment by TheJMan211** [comment]
My wife got a Macbook Air recently and I am using a TB16 dock. The Mac has the latest update, 10.15.2. I'm seeing behavior that it seems is different than what others describe. First, it never showed "Unsupported" for the dock in the System Information, but nothing worked anyway besides charging. I updated the dock firmware and now if I reboot the Mac with the docking station attached I get display on my DP monitor that I can extend or mirror but if the computer goes to sleep or turns off displays or is unplugged from the dock and plugged back in the display does not come back. Rebooting is the only way it comes back. In addition, none of the USB ports seem to work. Not using ethernet so I can't test that. I tried installing the unblocker anyway to see if it would get the USB working but I can't tell if it installed since it never said that it was unsupported anyway but the USB ports still don't work. I don't have an HDMI monitor to test with to find out if HDMI would work better than the DP.
