### ISSUE TITLE
Speeds

### ISSUE THREAD

**Issue by JacobAtchley** [rgov/Thunderbolt3Unblocker#56]
I've been testing this with a [Dell WD19TB dock](https://www.dell.com/en-us/work/shop/dell-thunderbolt-dock-wd19tb/apd/210-arik/pc-accessories). 
The ethernet port now works correctly; however the speeds aren't up to par. 

Before apply the unblocker i could get 900mb+ download using the [StarTech USB C Ethernet adapter](https://www.startech.com/Networking-IO/usb-network-adapters/usb-c-gigabit-adapter-white~US1GC30W).

After applying the unblocker, both the dell dock and the startech usb c adapter appear to only bond to 100mb instead of negotiating 1000mb connection. 

Just curious if anyone has seen a dip in speeds after applying this unblocker. Thanks!

**Comment by rgov** [comment]
It seems very unlikely to me that this is caused by this extension. The extension patches a small piece of code that is executed when the system enumerates the Thunderbolt device, i.e., asks it what kind of device it is. This patched code only runs once when the device is plugged in.

Also, the patch would not apply to the USB-C adapter, because it is not controlled by the Thunderbolt patch.

I *could* imagine that, now that the dock is unblocked, the other traffic on the bus (like display video and downstream USB ports) is making it so there's not enough bandwidth for the gigabit connection. But I don't know if this is what is happening. These decisions are done in other drivers, not the one patched by Thunderbolt 3 Unblocker.

**Comment by JacobAtchley** [comment]
@rgov thanks for the quick response. I'll keep experimenting and see if I can get the speeds back up. Thanks again!

**Comment by nielsson4711** [comment]
@JacobAtchley  I just passed by and maybe it's off-topic: 
If you aim to use SMB traffic with your tbt / ethernet adapter, please also inspect _/etc/nsmb.conf_ if SMB signing is enabled: 
```
[default]
signing_required=no  
```
The latest Mac OS updates seem to deploy the setting with value "no".
