### ISSUE TITLE
fails to work after restart

### ISSUE THREAD

**Issue by fifooo** [rgov/Thunderbolt3Unblocker#68]
followed instructions, and it does work on the same session. After a restart I get "your computer restarted due to a problem ..." and it goes back to "unsupported"

Please help

[t3u-diagnose.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/5969699/t3u-diagnose.txt)

**Comment by rgov** [comment]
It only unlocks devices that are plugged in *after* the extension is loaded. So if you reboot with the device already plugged in, it will not work. Just unplug the device and plug it back in again.

The software automatically detects if the system crashes due to Thunderbolt 3 Unblocker, and disables it. I see from your diagnostics that Thunderbolt 3 Unblocker is **not** the cause of your crash. However, the device you are unblocking *may be* the cause of the crash -- there is probably a reason why the device is blocked.
